//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSD {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSD.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Params 的本地化字符串。
        /// </summary>
        internal static string AdvancedParams {
            get {
                return ResourceManager.GetString("AdvancedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Lat/Lng 的本地化字符串。
        /// </summary>
        internal static string BadCoords {
            get {
                return ResourceManager.GetString("BadCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Tuning 的本地化字符串。
        /// </summary>
        internal static string BasicTuning {
            get {
                return ResourceManager.GetString("BasicTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot graph this field 的本地化字符串。
        /// </summary>
        internal static string CannotGraphField {
            get {
                return ResourceManager.GetString("CannotGraphField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cant detect your Board version. Please check your cabling 的本地化字符串。
        /// </summary>
        internal static string CantDetectBoardVersion {
            get {
                return ResourceManager.GetString("CantDetectBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking  的本地化字符串。
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check port settings or Port in use? 的本地化字符串。
        /// </summary>
        internal static string CheckPortSettingsOr {
            get {
                return ResourceManager.GetString("CheckPortSettingsOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Command failed to execute
        /// 的本地化字符串。
        /// </summary>
        internal static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Communication Error - no connection 的本地化字符串。
        /// </summary>
        internal static string CommunicationErrorNoConnection {
            get {
                return ResourceManager.GetString("CommunicationErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONNECT 的本地化字符串。
        /// </summary>
        internal static string CONNECTc {
            get {
                return ResourceManager.GetString("CONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Failed 的本地化字符串。
        /// </summary>
        internal static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting Mavlink 的本地化字符串。
        /// </summary>
        internal static string ConnectingMavlink {
            get {
                return ResourceManager.GetString("ConnectingMavlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description:  的本地化字符串。
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected a 的本地化字符串。
        /// </summary>
        internal static string DetectedA {
            get {
                return ResourceManager.GetString("DetectedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detecting Board Version 的本地化字符串。
        /// </summary>
        internal static string DetectingBoardVersion {
            get {
                return ResourceManager.GetString("DetectingBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DISCONNECT 的本地化字符串。
        /// </summary>
        internal static string DISCONNECTc {
            get {
                return ResourceManager.GetString("DISCONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloaded from internet 的本地化字符串。
        /// </summary>
        internal static string DownloadedFromInternet {
            get {
                return ResourceManager.GetString("DownloadedFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading from Internet 的本地化字符串。
        /// </summary>
        internal static string DownloadingFromInternet {
            get {
                return ResourceManager.GetString("DownloadingFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Epprom changed, all your setting will be lost during the update,
        ///Do you wish to continue? 的本地化字符串。
        /// </summary>
        internal static string EppromChanged {
            get {
                return ResourceManager.GetString("EppromChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Epprom format changed ({0) vs {1}) 的本地化字符串。
        /// </summary>
        internal static string EppromFormatChanged {
            get {
                return ResourceManager.GetString("EppromFormatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error closing log files 的本地化字符串。
        /// </summary>
        internal static string ErrorClosingLogFile {
            get {
                return ResourceManager.GetString("ErrorClosingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error communicating with the autopilot 的本地化字符串。
        /// </summary>
        internal static string ErrorCommunicating {
            get {
                return ResourceManager.GetString("ErrorCommunicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Connecting
        /// 的本地化字符串。
        /// </summary>
        internal static string ErrorConnecting {
            get {
                return ResourceManager.GetString("ErrorConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is not enabled in your firmware. 的本地化字符串。
        /// </summary>
        internal static string ErrorFeatureNotEnabled {
            get {
                return ResourceManager.GetString("ErrorFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading firmware file 的本地化字符串。
        /// </summary>
        internal static string ErrorFirmwareFile {
            get {
                return ResourceManager.GetString("ErrorFirmwareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error receiving log list 的本地化字符串。
        /// </summary>
        internal static string ErrorLogList {
            get {
                return ResourceManager.GetString("ErrorLogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: no responce from MAV 的本地化字符串。
        /// </summary>
        internal static string ErrorNoResponce {
            get {
                return ResourceManager.GetString("ErrorNoResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not connected. 的本地化字符串。
        /// </summary>
        internal static string ErrorNotConnected {
            get {
                return ResourceManager.GetString("ErrorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error receiving list
        /// 的本地化字符串。
        /// </summary>
        internal static string ErrorReceivingParams {
            get {
                return ResourceManager.GetString("ErrorReceivingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: command rejected by MAV 的本地化字符串。
        /// </summary>
        internal static string ErrorRejectedByMAV {
            get {
                return ResourceManager.GetString("ErrorRejectedByMAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error renaming file 的本地化字符串。
        /// </summary>
        internal static string ErrorRenameFile {
            get {
                return ResourceManager.GetString("ErrorRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error setting parameter  的本地化字符串。
        /// </summary>
        internal static string ErrorSettingParameter {
            get {
                return ResourceManager.GetString("ErrorSettingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set {0} Failed 的本地化字符串。
        /// </summary>
        internal static string ErrorSetValueFailed {
            get {
                return ResourceManager.GetString("ErrorSetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extended Tuning 的本地化字符串。
        /// </summary>
        internal static string ExtendedTuning {
            get {
                return ResourceManager.GetString("ExtendedTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create log - wont log this session 的本地化字符串。
        /// </summary>
        internal static string Failclog {
            get {
                return ResourceManager.GetString("Failclog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed download 的本地化字符串。
        /// </summary>
        internal static string FailedDownload {
            get {
                return ResourceManager.GetString("FailedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed read HEX 的本地化字符串。
        /// </summary>
        internal static string FailedReadHEX {
            get {
                return ResourceManager.GetString("FailedReadHEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read firmware.hex : 的本地化字符串。
        /// </summary>
        internal static string FailedToReadHex {
            get {
                return ResourceManager.GetString("FailedToReadHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed upload 的本地化字符串。
        /// </summary>
        internal static string FailedUpload {
            get {
                return ResourceManager.GetString("FailedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flight Modes 的本地化字符串。
        /// </summary>
        internal static string FlightModes {
            get {
                return ResourceManager.GetString("FlightModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Parameter List 的本地化字符串。
        /// </summary>
        internal static string FullParameterList {
            get {
                return ResourceManager.GetString("FullParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Parameter Tree 的本地化字符串。
        /// </summary>
        internal static string FullParameterTree {
            get {
                return ResourceManager.GetString("FullParameterTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GeoFence 的本地化字符串。
        /// </summary>
        internal static string GeoFence {
            get {
                return ResourceManager.GetString("GeoFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting  的本地化字符串。
        /// </summary>
        internal static string Getting {
            get {
                return ResourceManager.GetString("Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting FW List 的本地化字符串。
        /// </summary>
        internal static string GettingFWList {
            get {
                return ResourceManager.GetString("GettingFWList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting FW Version 的本地化字符串。
        /// </summary>
        internal static string GettingFWVersion {
            get {
                return ResourceManager.GetString("GettingFWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting Params 的本地化字符串。
        /// </summary>
        internal static string GettingParams {
            get {
                return ResourceManager.GetString("GettingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting Params... 的本地化字符串。
        /// </summary>
        internal static string GettingParamsD {
            get {
                return ResourceManager.GetString("GettingParamsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting updated parameters 的本地化字符串。
        /// </summary>
        internal static string GettingUpdatedParams {
            get {
                return ResourceManager.GetString("GettingUpdatedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Got param  的本地化字符串。
        /// </summary>
        internal static string Gotparam {
            get {
                return ResourceManager.GetString("Gotparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Alt 的本地化字符串。
        /// </summary>
        internal static string InvalidAlt {
            get {
                return ResourceManager.GetString("InvalidAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid BaudRate 的本地化字符串。
        /// </summary>
        internal static string InvalidBaudRate {
            get {
                return ResourceManager.GetString("InvalidBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Board Type 的本地化字符串。
        /// </summary>
        internal static string InvalidBoardType {
            get {
                return ResourceManager.GetString("InvalidBoardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Field 的本地化字符串。
        /// </summary>
        internal static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid FileName 的本地化字符串。
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number entered
        /// 的本地化字符串。
        /// </summary>
        internal static string InvalidNumberEntered {
            get {
                return ResourceManager.GetString("InvalidNumberEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Pan Range 的本地化字符串。
        /// </summary>
        internal static string InvalidPanRange {
            get {
                return ResourceManager.GetString("InvalidPanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid PortName 的本地化字符串。
        /// </summary>
        internal static string InvalidPortName {
            get {
                return ResourceManager.GetString("InvalidPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Tilt Range 的本地化字符串。
        /// </summary>
        internal static string InvalidTiltRange {
            get {
                return ResourceManager.GetString("InvalidTiltRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Update Rate 的本地化字符串。
        /// </summary>
        internal static string InvalidUpdateRate {
            get {
                return ResourceManager.GetString("InvalidUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link Stats 的本地化字符串。
        /// </summary>
        internal static string LinkStats {
            get {
                return ResourceManager.GetString("LinkStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please click ok and move the autopilot around all axises in a circular motion 的本地化字符串。
        /// </summary>
        internal static string MagCalibMsg {
            get {
                return ResourceManager.GetString("MagCalibMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mavlink Connecting... 的本地化字符串。
        /// </summary>
        internal static string MavlinkConnecting {
            get {
                return ResourceManager.GetString("MavlinkConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are missing data points. do you want to run the calibration anyway? 的本地化字符串。
        /// </summary>
        internal static string MissingDataPoints {
            get {
                return ResourceManager.GetString("MissingDataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Firmware 的本地化字符串。
        /// </summary>
        internal static string NewFirmware {
            get {
                return ResourceManager.GetString("NewFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New firmware available
        /// 的本地化字符串。
        /// </summary>
        internal static string NewFirmwareA {
            get {
                return ResourceManager.GetString("NewFirmwareA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No FMT message for  的本地化字符串。
        /// </summary>
        internal static string NoFMTMessage {
            get {
                return ResourceManager.GetString("NoFMTMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only 1 Heatbeat Received 的本地化字符串。
        /// </summary>
        internal static string Only1Hb {
            get {
                return ResourceManager.GetString("Only1Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only 1 Mavlink Heartbeat Packets was read from this port - Verify your hardware is setup correctly
        ///Mission Planner waits for 2 valid heartbeat packets before connecting 的本地化字符串。
        /// </summary>
        internal static string Only1HbD {
            get {
                return ResourceManager.GetString("Only1HbD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please connect first 的本地化字符串。
        /// </summary>
        internal static string PleaseConnect {
            get {
                return ResourceManager.GetString("PleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please connect and backup your config in the configuration tab. 的本地化字符串。
        /// </summary>
        internal static string PleaseConnectAndBackupConfig {
            get {
                return ResourceManager.GetString("PleaseConnectAndBackupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please load a valid file 的本地化字符串。
        /// </summary>
        internal static string PleaseLoadValidFile {
            get {
                return ResourceManager.GetString("PleaseLoadValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a cell first 的本地化字符串。
        /// </summary>
        internal static string PleaseSelectCell {
            get {
                return ResourceManager.GetString("PleaseSelectCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Please upgrade 的本地化字符串。
        /// </summary>
        internal static string Pleaseup {
            get {
                return ResourceManager.GetString("Pleaseup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sucessfully programmed 的本地化字符串。
        /// </summary>
        internal static string ProgrammedOK {
            get {
                return ResourceManager.GetString("ProgrammedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raw Param Warning 的本地化字符串。
        /// </summary>
        internal static string RawParamWarning {
            get {
                return ResourceManager.GetString("RawParamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All values on this screen are not min/max checked. Please double check your input.
        ///Please use Standard/Advanced Params for the safe settings 的本地化字符串。
        /// </summary>
        internal static string RawParamWarningi {
            get {
                return ResourceManager.GetString("RawParamWarningi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Hex 的本地化字符串。
        /// </summary>
        internal static string ReadingHex {
            get {
                return ResourceManager.GetString("ReadingHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Hex File 的本地化字符串。
        /// </summary>
        internal static string ReadingHexFile {
            get {
                return ResourceManager.GetString("ReadingHexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received List 的本地化字符串。
        /// </summary>
        internal static string ReceivedList {
            get {
                return ResourceManager.GetString("ReceivedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 run anyway 的本地化字符串。
        /// </summary>
        internal static string RunAnyway {
            get {
                return ResourceManager.GetString("RunAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a comport 的本地化字符串。
        /// </summary>
        internal static string SelectComport {
            get {
                return ResourceManager.GetString("SelectComport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show me again? 的本地化字符串。
        /// </summary>
        internal static string ShowMeAgain {
            get {
                return ResourceManager.GetString("ShowMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard Params 的本地化字符串。
        /// </summary>
        internal static string StandardParams {
            get {
                return ResourceManager.GetString("StandardParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your model is still moving are you sure you want to disconnect? 的本地化字符串。
        /// </summary>
        internal static string Stillmoving {
            get {
                return ResourceManager.GetString("Stillmoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout waiting for autoscan/no mavlink device connected 的本地化字符串。
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying to connect.
        ///Timeout in {0} 的本地化字符串。
        /// </summary>
        internal static string Trying {
            get {
                return ResourceManager.GetString("Trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Units: {0}{1} 的本地化字符串。
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Found
        ///
        ///Do you wish to update now? [link; 的本地化字符串。
        /// </summary>
        internal static string UpdateFound {
            get {
                return ResourceManager.GetString("UpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Now 的本地化字符串。
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Complete 的本地化字符串。
        /// </summary>
        internal static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading {0} bytes to Board: 的本地化字符串。
        /// </summary>
        internal static string UploadingBytesToBoard {
            get {
                return ResourceManager.GetString("UploadingBytesToBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload succeeded, but verify failed: exp {0} got {1} at  的本地化字符串。
        /// </summary>
        internal static string UploadSucceededButVerifyFailed {
            get {
                return ResourceManager.GetString("UploadSucceededButVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Complete 的本地化字符串。
        /// </summary>
        internal static string VerifyComplete {
            get {
                return ResourceManager.GetString("VerifyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Firmware 的本地化字符串。
        /// </summary>
        internal static string VerifyFirmware {
            get {
                return ResourceManager.GetString("VerifyFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning, as of AC 3.1 motors will spin when armed, configurable through the MOT_SPIN_ARMED parameter 的本地化字符串。
        /// </summary>
        internal static string WarningAC31 {
            get {
                return ResourceManager.GetString("WarningAC31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning, if you are installing AC 3.2 for the first time you MUST redo a Compass calibration. 的本地化字符串。
        /// </summary>
        internal static string WarningAC32 {
            get {
                return ResourceManager.GetString("WarningAC32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Browse will not function correctly without FMT messages in your log.
        ///These appear to be missing from your log. 的本地化字符串。
        /// </summary>
        internal static string WarningLogBrowseFMTMissing {
            get {
                return ResourceManager.GetString("WarningLogBrowseFMTMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning rally points are located greater than RALLY_LIMIT_KM 的本地化字符串。
        /// </summary>
        internal static string Warningrallypointdistance {
            get {
                return ResourceManager.GetString("Warningrallypointdistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Params
        ///DON&apos;T DO THIS IF YOU ARE IN THE AIR
        /// 的本地化字符串。
        /// </summary>
        internal static string WarningUpdateParamList {
            get {
                return ResourceManager.GetString("WarningUpdateParamList", resourceCulture);
            }
        }
    }
}
